### ISSUE TITLE
Beskar AA vehicle

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#1]
Leaving this here for Cannon to see,

Beskar would like a replacement AA vehicle so we're not fielding a warden for solely that in case a zeus doesn't like the idea of us using it with it's rearming capability. Anything like how the old 501st AA longbow worked or looked is pretty solid, AA guns and AA missiles (limited more so than the main AA gun ammo, mostly for the more wild flying hostile aircraft that are harder to nail)

**Comment by liamcannon** [comment]
I have a vic in the works but there's also the AA variant of the warden.

**Comment by DoctorDrugs** [comment]
See issue#11 as to why we can’t use the warden as an AA vehicle currently as a stop gap
