### ISSUE TITLE
.model error with 91st LAAT MK2 (MRC_unarmed_LAAT)

### ISSUE THREAD

**Issue by Baconbitz94** [91st-Aux-Team/MRC-issue-tracker#10]
**Describe the bug**
Seems to be the exact issue that occurred in https://github.com/91st-Aux-Team/MRC-issue-tracker/issues/7 (the bantha .model error) 

**To Reproduce**
1. make a mission file with a LAAT MK2 present
2. load the above described mission file in eden (or on a deddy server)
3. receive .model error in eden, mission file wont load on server

**Expected behavior**
would expect to be able to have LAATs on mission file for content purposes

**Screenshots**

**Mod List**
attached as notepad

**Additional context**
Did not reproduce on server (since it requires an uploaded mission file) but I can do that if needed for troubleshooting (I am assuming its a similar cause to the Bantha but ofc Im dumb so could be wrong). Unsure if this affects our other LAATs but betting it does
[91stmm.txt](https://github.com/91st-Aux-Team/MRC-issue-tracker/files/12528027/91stmm.txt)

**Comment by liamcannon** [comment]
@Baconbitz94 I took a look and couldn't find the same issue as the bantha. The rewrite is getting to a point where it can start to be tested on the c4 dev server so we'll see if this has resolved itself.

**Comment by Baconbitz94** [comment]
Copy that, Il watch for when it gets thrown on there and do some more in depth tests on it o7

**Comment by liamcannon** [comment]
@Baconbitz94 can you load the test mod with the current LAAT and see if this is still an issue.

**Comment by Baconbitz94** [comment]
Il get with Miller for access to that, used to have it but I did a mod purge a couple months ago and cant find it anymore

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by liamcannon** [comment]
Closing this, update seems to have resolved the issue.
