### ISSUE TITLE
91st Warden Gun is forced to max zoom and cannot be unzoomed

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#11]
**Describe the bug**
exactly as the title of the bug report, warden is unusable as an AA piece due to this.

**To Reproduce**
1. Get in gunner seat of the warden
2. Use weapon zoom notice it's super zoomed in and barely rotates
3. have to rely on 3rd person to move the weapon

**Expected behavior**
be able to sit in the gunner seat and zoom in and out without issue.

**Screenshots**
N/A

**Mod List**
91st MRC main modlist

**Additional context**

**Comment by DoctorDrugs** [comment]
327th, 501st, 212th, etc all have this bug

**Comment by liamcannon** [comment]
@DoctorDrugs start unloading aux mods and see if doing that fixes it
