### ISSUE TITLE
Peaceable Explosives not Linking to Detonators.

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#12]
**Describe the bug**
The [MRC] DB-7 Demolition Charge only connects with the [MRC] Explosive Firing Device
The C12 Demolition Charge & DP-3 Demolitions Pack, work with the M152 Firing Device.
The Explosives Mentions do not connect to the other Detonator Listed. An ENG currently would need to run both detonators to effectively use the explosives. 

**To Reproduce**
1. Go to Eden Editor
2. Equip a Loadout with the "C12," "DB-7," "DP-3," "[MRC] EFD," & "M152 FD"
3. Place all explosives as the player, and attempt to link them to the Firing Devices.

**Expected behavior**
Expected all three of the Explosives to Link to Both/One of the Explosive Firing Devices.

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/56cfaa71-7e32-4b38-97ec-3c4a649bce30)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/3b4b4dc7-f4f0-48ab-8b88-bf53183d2c11)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/774c470b-a488-4c17-b48e-ac6c31b64bef)

**Mod List**
Main Modlist + some Clientsides. (Cant Link at this time, if still needed I can Send my HTML through Discord)

**Additional context**
I've Attempted to run the Explosives in question in Operations for testing, but never had the chance to use them in the field. Only after I mentioned to the Eng Qual Lead, that there was a new Breaching Charge for him, did he let me know about the Detonator issue. Also would like to know what the [MRC] EFD Range is.

**Comment by liamcannon** [comment]
I dug into this a while ago and the += operand used inside of ace_triggers doesn't work as intended so I couldn't add the new clacker to existing charges. The solution is to either remove the custom clacker and use the m152 or write new versions of the current explosives using the mrc clacker
