### ISSUE TITLE
91st bacta tank (destroyed) throwing error in eden/server (MRC_bacta_tank_w)

### ISSUE THREAD

**Issue by Baconbitz94** [91st-Aux-Team/MRC-issue-tracker#13]
**Describe the bug**

**To Reproduce**
1. make a mission file including the MRC_bacta_tank_w 
2. save it, then either load it up on server or open again in editor
3. see the error Size:'cargoPreciseGetInOut/' not an array (seems to -almost- break the file, after a couple of attempts the server loaded the file but unsure if other players would be able to get in)

**Expected behavior**
low prio, but I would expect our assets to not throw errors when possible

**Screenshots**
here is a shot of the error on the MainOp server (if needed for logging taken at 1101am PST on 9/24)
![bactaerror](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/143630633/8d755fc4-af8a-4bbc-a785-340386603438)

**Mod List**
attached is a notepad of the modlist used to make the mission file (the error occurs on that modlist as well as my client one) 
[91stmm.txt](https://github.com/91st-Aux-Team/MRC-issue-tracker/files/12709417/91stmm.txt)

**Additional context**
Super low prio, but I thought it worth reporting in case it is an easy fix. Additionally, this error doesnt seem to pop on the un-destroyed bacta tank MRC_bacta_tank

**Comment by liamcannon** [comment]
@Baconbitz94 It'll get fixed with the roll out of MRC Auxiliary
