### ISSUE TITLE
[MRC] Props - Banners

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#16]
**Describe the bug**
The Banners in the Test Mod are showing up as the 3AS Landing Pad with the Banner Textures.

**To Reproduce**
1. Go to Load Main Op Modlist,  & Replace 85th, 91st Mod, and 91st Ace Compat.
2. Click on 'Spawn in a Banner under [MRC] Props
3. See error

**Expected behavior**
Old Style Banners.
**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/fb2a8c89-2d94-4718-aad5-5b17e4f9e385)

**Mod List**
Main Op Modlist, Removed 85th Aux Mod, 91st Main Aux Mod, 91st Ace Compat. & Loaded Testing Mod
**Additional context**

**Comment by liamcannon** [comment]
Resolved in next update
