### ISSUE TITLE
[MRC] Chaingun issues

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#19]
Excessive amount of smoke/explosions from round impacts when using the chaingun. The impact from one round is akin to something like a thermal detonator.

https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/0b634426-3297-4939-bce4-7fdf2bc45228

**Comment by liamcannon** [comment]
😃 looks good to me

I can lower the smoke cloud.
