### ISSUE TITLE
Cannon's requested vehicle testing/feedback

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#20]
**91st MRC**
_Tested against 91st CIS and in some cases where 91st CIS vehicles were missing 3AS stand ins (HMP/MTT)_

Crism (AA vic)
- Main cannon deviation is too high to be considered as effective AA anything out past 500-600m is just spray and pray to hit anything
- Main cannon when pinning the trigger causes a series of rapid flashes in the gunner's sight from the muzzle flash, hard to notice but could be a problem with anyone at risk of seizures
- using page up/down "sets the range" anything under 200 set means shooting left of the sight, anything over 750 is center and high, 500-600 about right for center of the target regardless of range currently
- multiple hits to bring down HMPs, vultures, etc (Feels good to me)

New Kunda
- Main cannon sound is off by about 1-2 seconds, round is sent down range then the fire/reload noise is played, reloading sound trails into the time the next shot can be fired as well (most likely due to the sound being played late)
- HE rounds missing reload sound
- APFSDS rounds are worse to use against Heavy AATs then HEAT rounds, HEAT taking 2 rounds while APFSDS rounds take 3-4 rounds to destroy (I am not worrying about component damage values currently, I can test for those specifically another time if required or wanted). More testing revealed the APFSDS rounds are worse to use than HEAT rounds across the board, APFSDS rounds overpen majority if not all targets including MTTs
- HEAT rounds have little splash damage if at all
- Main cannon lost the ability to reasonably damage MTTs
- Turret coax is slow firing AP? rounds, hard to use to defend itself from AT infantry. 
- Turret coax rounds have gravity and drop semi fast
- Commander gun is 75 round mags with 3 extra mags, 100 rounds would be preferred with an increase to the spare rounds from 3 mags to 5 mags 

Recon Saber
- good luck hurting anything sturdier than a B-2 (you won't)

Saber
- Main Cannon deals 8% damage from the front weak spot to regular AATs and 5% damage to Heavy AATs, Rear weak spots are 15% to regular AATs and 8% Heavy AATs
- HE rounds could in theory be used to track both AAT models after about 10-14 shots
- HE rounds high tendency to bounce off surfaces
- Commander seat MG have to turn in to use it, Commander seat CANNOT be aimed reliably, low ammo count as the same with the kunda Commander seat

Super Saber
- Main Cannon weapon sound sync'd to firing BUT the reloading sound goes past when the next round is ready to fire and cuts off the ending abruptly to trigger the next shot sound
- Main Cannon shoots incredibly low at all distance settings, however pressing t before firing to set range distance on the main cannon fixes this. (completely impractical to press t just to reasonably use the weapon before firing every time)
- Lack of Coax MG
- APFSDS overpen issue on all vehicles worse than HEAT
- HEAT overpen issue on everything smaller than a MTT
- HE rounds track in 3 shots on AATs
- HE splash radius less than the regular saber splash
- longer TTK than a kunda by a considerable amount

Both Saber and Kunda vehicles you cannot select the ammo for the turret gun in the commander seat even though the scroll wheel prompt pops up to do so, it does nothing when clicked.

**Comment by DoctorDrugs** [comment]
Forgot to mention tested with tester mod loaded on top of the normal modlist using the newer vehicles

will test UTAT at a later date

Warden turret broken/unusable

Vehicle overall engine performance is underwhelming compared to current versions in the live mod

**Comment by DoctorDrugs** [comment]
Majority of these issues are still valid especially with the Super Saber's lack of MG and lack of spare magazines for the MGs on the other vehicles' coax in prolonged combat.

The regular Saber could use an additional magazine or two for Anti Tank ammo to be in line with the flow and general pacing of our operations.

**Comment by DoctorDrugs** [comment]
Tested Crism in operation today, unless the vehicle is locked onto a target and getting weapon lead the main cannons spread all over the place. When locked on the main cannon is dead accurate.

Crism has vanilla stuff inside the vehicle's inventory.

**Comment by DoctorDrugs** [comment]
Issues have started to pop up with the ATGMs, they're incredibly squirrely will rapidly jump up and down making it impossible to hit anything at any distance that isn't the size of  a 3 story building.

**Comment by Grizzly-github** [comment]
@liamcannon assign me to this ill start crawling through it as the aircraft are fixed :p

tomorrow...

**Comment by DoctorDrugs** [comment]
Saber spawning without it's AP rounds and needs to be rearmed to get them when spawned in.
Crew being knocked uncon when getting shot at by AATs in most armored vehicles, vehicles explode and the crew are forced to respawn.

**Comment by DoctorDrugs** [comment]
Can I get a response here in terms of when some of these are gonna be addressed/looked at? It’s been a while of asking regarding about certain things being fixed on vehicles now like a machine gun coax for the gunner of the super saber and an example.

**Comment by Durzai** [comment]
I will be assigned to this project from here on out, I will start working through the feedback as soon as I can.

Apologies for the lack of communication the past few months, it will be rectified as soon as possible.

**Comment by Durzai** [comment]
Crism

- Main cannon deviation is too high to be considered as effective AA anything out past 500-600m is just spray and pray to hit anything. (Dispersion will be reduced from 0.002 to 0.001 pending further testing to see if this helps with the issue).

**Comment by Durzai** [comment]
Kunda

- Turret coax rounds have gravity and drop semi fast. (coefGravity reduced from 1 to 0.1, bullet drop should be negligible now).
- Commander gun is 75 round mags with 3 extra mags, 100 rounds would be preferred with an increase to the spare rounds from 3 mags to 5 mags. (Commander gun has 3x 300Rnd magazines, assuming this was referencing the Gunner Coaxial HMG, which has had it's total magazines increased from 4 to 5, for a total of 500 rounds. If a further increase is needed, please let me know).

**Comment by Durzai** [comment]
Super Saber

- Lack of Coax MG. (12.7mw Coaxial HMG has been added to the Super Saber with 5x 100Rnd magazines).
