### ISSUE TITLE
Muddy's Helmet is missing

### ISSUE THREAD

**Issue by Grizzly-github** [91st-Aux-Team/MRC-issue-tracker#21]
**Describe the bug**
Muddy's Helmet is missing from the custom helmets section.

**To Reproduce**
1. Go to 'Helmets'
2. Click on '91st Custom Helmets'
3. Scroll down to 'See all the helmets and see Muddy's isn't there'

**Expected behavior**
I Expected to see Muddy's Helmet there.

**Screenshots**
![5dd06e418f0142757698997902a1a345](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/36320706/fd0c13d6-4fb8-4a10-8c1f-665adde2b483)

**Mod List**
Main Op

**Additional context**
:)

**Comment by liamcannon** [comment]
Sorry Muddy 😞 its in for next week.
