### ISSUE TITLE
Anomalies with Test Mod Build Launched on  — 11/19/2023

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#22]
CIS Argons
---
**Describe the bug**
CIS Argon Fuel Truck Labeled in Eden as "Argon Devise Transport"

**To Reproduce**
1. Go to 'Eden'
2. Click on 'OPFOR, Type MRC'
3. Scroll down to 'See Error'

**Expected behavior**
Name of CIS Fuel Transport to be Fuel Transport

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/7b572391-1e59-483d-b69c-c7993121fc7a)

**Mod List**
Main Op Modlist, - 91st Aux, 91st Compat, & 85th Aux. + 91st Test Mod

**Additional context**

"MRBC Mk-1 GroundHolder"
---
**Describe the bug**
Unknown if Placeholder for something, unknown if you know its here. 
Spannable  "Prop" under "[MRC] Statics" folder

**To Reproduce**
1. Go to 'Eden'
2. Click on 'Props, Type MRC'
3. Scroll down to '[MRC] Statics'
4. Spawn [MRC] MRBC Mk-1 GroundHolder
5. See error

**Expected behavior**
Unknown

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/8754c244-839e-4275-b61e-6f56e97ab93c)

**Mod List**
Main Op Modlist, - 91st Aux, 91st Compat, & 85th Aux. + 91st Test Mod

**Additional context**
Unknown if they are being keep as Place Holder or not. Reporting to make sure Team is Aware.

"[MRC] Supplies"
---
**Describe the bug**
Old supply Boxes still around, with same Textures, 

1. Go to 'Eden'
2. Click on 'Props, Type MRC'
3. Scroll down to '[MRC] Supplies'
4. Spawn Everything under the Folder
5. See error

**Expected behavior**
Removal of Old/Retexture of Old Supply boxes

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/5552bb49-1179-4593-ba0f-431ffac07741)
(Left to Right) "[MRC] Resupply Box (Ammo), [MRC] Resupply Box (Explosives), [MRC] Resupply Box (Medical), Ammo Crate, Explosives Crate, Jade Crate, Medical Crate, Mixed Crate, Rocket Crate.

**Mod List**
Main Op Modlist, - 91st Aux, 91st Compat, & 85th Aux. + 91st Test Mod

**Additional context**
Unknown if they are being keep as Place Holder or not. Reporting to make sure Team is Aware.

"ACE + Zeus Not Working"
---
**Describe the bug**
Attempting to Load into Eden to Test Weapons, Vehicles, & Inventories. A Few Errors are Displayed. And  After hitting OK Text is Displayed on Screen. Once Control of the Character is Given, Zeus will not Launch, and Ace Interacts will not work.

1. Go to 'Eden, New Map'
2. Click on 'Spawn Character & Gamemaster Module, Link them, & Make sure to Allow ALL ADDONs under the Module.'
3. Scroll down to 'Start Scenario by hitting Enter'
4. See Errors

**Expected behavior**
Zues & Ace Interacts be Given/working

**Screenshots**
Error 1, & Text 1
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/b39eade4-071a-486e-a710-b47ba9f869dc)

Text 2
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/1805b065-bc4c-4d05-9330-f52a3f42401e)

Error 2 (Displayed after Leaving Senario, apon seeing Eden Editor Screen Again)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/7215fd9f-5336-4973-9470-8a78447aaf48)

**Mod List**
Main Op Modlist, - 91st Aux, 91st Compat, & 85th Aux. + 91st Test Mod

**Additional context**
1. Sorry for Late Report. I Initially though this was an Error on my End Attempted to Repair & Validate Files. Error still Occurred. 
I then Spoke to other Testers to see if they had this Error as well. They Did, so here is the Report.
2. ACE Arsenel will not Load Threw the Main Menu. The Displayed Error
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/0c123fbb-d884-42ca-b38a-e7df3e6272f2)

"Changelog"
---
**Describe the bug**
Unable to Locate/See, the Added/Removed Assets from the Changelog on 11/19/2023

**To Reproduce**
Open Eden 

**Expected behavior**
New Vehicles/ Spawnable Assets for Opfor and Bluefor

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/2bdf8594-286f-4ddd-ab92-1fcbbafa2c12)

Bluefor
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/90440987-8808-4165-a059-a6b95396dd1c)

Opfor
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/3b0e6796-7d38-4049-a90b-2d6bce82fcd2)

Greenfor
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/3a1598bb-8442-42e8-b41e-8ae8d57b951b)

Civilian
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/a2094bf5-f2bd-401b-803c-4e868c79c6b1)

Props
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/fc68f5a7-ca44-4b23-a47d-79c43990c4e5)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/1b3aa249-9fcd-49df-9e2b-8dcd8bea6eb0)

**Mod List**
Main Op Modlist, - 91st Aux, 91st Compat, & 85th Aux. + 91st Test Mod

**Additional context**
Have not been able to Check Arsenal Yet. For Weapon/Armor Change
Musket is still Present under Vanilla Arsenel.
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/5e388180-a346-47bc-87e6-cf4e093213c5)
Can Not Locate NOVA Uniforms/Helmets

**Comment by liamcannon** [comment]
@xxQal When testing, unload the main 91st mod, 91st compat, and 85th. Only load the test mod. That's the reason you're still seeing the musket.

**Comment by xxQal** [comment]
The Entire time I did not have the 91st Aux Mod, The 91st Compat, NOR the 85 Mod. I will Post the Modlist in 1 Sec.
@liamcannon

**Comment by xxQal** [comment]
file:///C:/Users/xqalb/Downloads/Qal's%20Testing%20Modlist.html
