### ISSUE TITLE
Squad Assault vehicle

### ISSUE THREAD

**Issue by DJGeneralE** [91st-Aux-Team/MRC-issue-tracker#29]
**Is your feature request related to a problem? Please describe.**
Cstaff is looking for a vehicle that would be similar to a squad humvee so 5-6 seats with a z6 or grenade launcher on the roof
**Describe the solution you'd like**
Cstaff is looking to add mobility to the squads in a way that can be operated the squad with only 2 vehicles
**Describe alternatives you've considered**
something like the vanilla ifrit would work 
**Additional context**

**Comment by Grizzly-github** [comment]
RATT will supplement this.

**Comment by liamcannon** [comment]
Will be named the Dewback
