### ISSUE TITLE
Helmets/Armor etc that needs to be removed 8/28 4.19 update.

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#3]
Items still in the mod that need to be removed/hidden.

Trill's Vest and NVG
Main's Armor
Saint Armor
Penguin Armor

P2 Helmets
Miller
Snapper
Bardok
Saint
Penguin

BARC Helmets
Snapper
Shogun

**Comment by liamcannon** [comment]
@PulyiD can you do this
