### ISSUE TITLE
[FEAT] Scale up the B2 Model

### ISSUE THREAD

**Issue by Traumaura** [91st-Aux-Team/MRC-issue-tracker#30]
**Is your feature request related to a problem? Please describe.**
B2's currently are shorter than the players, making them comical rather than threatening.

**Describe the solution you'd like**
Scale their model up to stand up to a third taller than the player model.

**Describe alternatives you've considered**
Leave them as little shrimpy boys for the meme.

**Additional context**
Baby B2 doo doo doo doo doo.

**Comment by liamcannon** [comment]
I can't scale the b2 model as it currently is, we'll look into alternative options.
