### ISSUE TITLE
Change Rocket Weight

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#32]
**Is your feature request related to a problem? Please describe.**
So, Our Old AT were allowed to carry 4 AT Rockets, Would be able to deal with 1-Heavy AAT, and 1-2 Light Vehicles.
So in a Squad ~2-3 Heavy AATs OR ~8 Light Vehicles could be dealt with.

In the Current Build of the Mod. It takes 2-3 Tandem Rockets to Deal with Heavy AATs. 1-3 HEAT Rockets to Deal with AATs Other Light Vics. 
I Would Propose that AT Be Carrying x2 Tandem, x3 HEAT, & x2 of FRAG/HEP.  Which would Equal ~1-2 Heavy Assets, and ~2-4 Light Vehicles a Squad could take care of.  
In Our Current Mod, a Full Rifleman Kit Offers about 18lbs of Space for Rockets. 

**Describe the solution you'd like**
I'm Suggesting that The Frag & HEP: 1.5lbs. | HEAT: 2lbs | Tandem: 4lbs.  Instead of the 4lbs, 7lbs, & 5lbs. They Currently are.

**Describe alternatives you've considered**
Requesting a New Backpack to be even Heavier then we were beforehand. 
Only Carrying Tandem Rounds. (x2 could be Carried, and 1 extra that isn't tandem.)

**Additional context**
Just Trying to utilise all of our new equipment, and be as effective as we were before this update.

**Comment by liamcannon** [comment]
Rocket changes were pushed to the testers mod last night that included significant buffs to all rockets. Tandem mag size was changed from 7 to 6 lbs, HEAT was changed to 4 lbs I think?
