### ISSUE TITLE
Issues with DC17/A 8/28 4.19 update

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#4]
DC17 is still able to fire 3 round HE grenades
DC17A is unable to fire smoke or flare grenades

And then what are we doing with the black nebula revolver?

![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/a863d182-96d6-4fed-9976-cf1396813cd7)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/b4046353-bdf7-4158-8d24-fc0282f467d9)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/c461aa12-bbed-4d6d-a286-d9abaa9ba606)

**Comment by liamcannon** [comment]
I know hex did this already, I just have to merge the branch he did it on.

**Comment by liamcannon** [comment]
Resolved in Rewrite
