### ISSUE TITLE
DC-15C Stuns

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#41]
**Describe the bug**
DC-15C does not have the Ability to shoot stun Rounds

**To Reproduce**
Open Arsenal, Select MRC DC-15Cm Check Available Ammo.

**Expected behavior**
The Option to shoot stun rounds like the other Riflemen Primary Weapons.

**Screenshots**

**Mod List**
The Main Op Modlist in Discord. -91st Aux, +91st Test

**Additional context**
Can Include Image if you want me too.

**Comment by liamcannon** [comment]
Grizzly added an MRC stun I think it might be a better idea to just add the JLTS stun muzzle and mag instead of making a whole new one to do the exact same thing with just a different name.
