### ISSUE TITLE
Issues with UGLs in current test build.

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#42]
DC-15A GL has grenades in primary magazine slot.

![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/e3314181-ca1c-4107-a3eb-b26f542272b8)

Missing the blue effect on HE, HEF and HEAB rounds when fire from all launchers.

Also just to include it here, is it possible to add smaller increments to the 15A gl sight similar to the Wester/15c? Ie 50-75-100-150 etc

**Comment by liamcannon** [comment]
Eye points for the sight are done in both config and the memory LOD of the weapon, I can't edit the memory lod so if I did make the changes the eye optics would probably be off.
