### ISSUE TITLE
[MINOR] Jump Script Visual Bug

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#43]
**Describe the bug**
The Jump scrip has the name of the equiped backpack show on all JT Varriants other then the JT12-Teamlead

**To Reproduce**
Load Arsenal, Chose any "JumpTrooper Backpacks" See they have the name on the Scrip. The Teamleader does not.

**Expected behavior**
Name of Backpack on the Scrip Display

**Screenshots**
JT-12-TEAMLEADER
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/4062f03f-8abb-4c21-9666-15995b0667a7)
CDV.
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/5545f63c-6afe-47b5-aacc-ac688e7f6df9)
JT-12
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/26e2d86d-4965-4f6d-96ae-94ad11dc6287)

**Mod List**
MAIN OP: -91st Aux, +91st Test

**Additional context**
This is nothing but Visual. Just a Minor Inconvenience.
CDVs also have the Name displayed on the Scrip Visual. The only one missing is the Team Leader JT-12.

**Comment by Grizzly-github** [comment]
fixed
