### ISSUE TITLE
[MRC] Valken-38X secondary optic bug

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#45]
When using the secondary aiming mode (aiming over the scope) on the Valken the rounds fire up at an angle. Unsure if it's intended to be able to use the front sight post or not

![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/a8f54b43-94a2-420f-a43c-a9fe753b50cf)

**Comment by liamcannon** [comment]
@IchBinMiller can you reproduce this with the standard 3AS Valken?

**Comment by IchBinMiller** [comment]
> @IchBinMiller can you reproduce this with the standard 3AS Valken?
![20240109042156_1](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/76767512/573955a9-cc53-4447-ac5f-c22c3e895a62)

Same thing with the 3AS Valken

**Comment by liamcannon** [comment]
If you unload the test mod, is the behavior the same? @IchBinMiller

**Comment by IchBinMiller** [comment]
@liamcannon Without the test mod it's the same so I guess it's a 3AS issue.
