### ISSUE TITLE
[MRC] Supply Boxes 

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#46]
**Describe the bug**
There are several Missing/"PREMIUM" Items from Supply Boxes.

**To Reproduce**
Place a LAAT, ACE Cargo Unload the Supply Boxes.

**Expected behavior**
No Premium Items and Enough Supplies for at Minimum a Squad to Resupply off of, if not the Platoon.
Ammo Box Issues: 
Item Name | Item Quantity | Notes
-- | -- | --
MRC_65x39_Ball_x100 | 20 | MISSING From Crate but in Code (What is this Item?)
Stun | 10 | REMOVE FROM CODE
Flamthrower Fuel | 3 | REMOVE FROM CODE
Chaingun | 3 | REMOVE FROM CODE
Chaingun HE | 3 | REMOVE FROM CODE
E-Web | 2 | REMOVE FROM CODE

Explosive Box Issus:
Item Name | Item Quantity | Notes
-- | -- | --
Premium Item | 30 | IN The Box? Anyone have a Clue
-|-|-
GL 3Rnf Flare | 10 | REMOVE FROM CODE
GL 3Rnd Flare (Orange) | 5 | REMOVE FROM CODE
GL_G77 | 10 | MISSING From Crate but in Code
GL_G76 | 10 | MISSING From Crate but in Code
GL_G75 | 10 | MISSING From Crate but in Code
IK55 HEAT | 20 | MISSING From Crate but in Code

Medical Box Issues:
Item Name | Item Quantity | Notes
-- | -- | --
Bacta 250ml |   | Remove from Code?

**Screenshots**
Ammo Box Outside:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/373e2833-db68-41ac-a53b-159119ba16aa)
Ammo Box Contents:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/aeb2524c-2e38-43d4-a1ef-daa25ffeb42b)
Explosive Box Outside:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/a1f27a5a-6720-45cd-a306-42bad497aa07)
Explosives Box Contents:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/0bac6646-0c82-4b83-a28a-832aa0436b41)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/53244039-df4b-4a83-ad36-d228fdc4a5dd)
Medical Box Outside:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/2bf6e9e7-23ef-4eb9-9172-08db4662c0cf)
Medical Box Contents:
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/b02fe1e7-4819-4105-af8a-d34ce21e771b)

**Mod List**
MAIN OP: -91st Aux, +91st Test

**Additional context**
Grizzly Informed me of what was supposed to be in the Boxes. I Cross Referenced & Attempted to figure out what was MIA

**Comment by xxQal** [comment]
I Finally Finished Cross referencing what Grizzly Gave me, & Found The Anomalies.

**Comment by xxQal** [comment]
Wrong Button

**Comment by Grizzly-github** [comment]
oh cool

**Comment by Grizzly-github** [comment]
everything is finished except HEAT Rockets dont know why they won't spawn
