### ISSUE TITLE
Z-95 Arsenal Not Uniform/Reverted

### ISSUE THREAD

**Issue by VexTheSunBro** [91st-Aux-Team/MRC-issue-tracker#47]
**Describe the bug**
Z-95 Armaments should replicate and utilize most of the same selection as the ARC-170 but currently does not within the Pylon system
**To Reproduce**
1. Make Z-95, Arc-170 and Warden
2. Configure Pylons
3. Select Options

**Expected behavior**
Same armaments with more quantity on ARC-170

**Screenshots**

**Mod List**
Standard Modlist with Tester Mod

**Additional context**

**Comment by Grizzly-github** [comment]
this is reverted
