### ISSUE TITLE
Remove MRC Droid Lock on AT Launcher

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#48]
**Describe the bug**
The 91st MRC Droid lock on AT launcher exists.

**To Reproduce**
1. Go to Arsenal grab a Droid launcher or spawn 91st ?Heavy? AT Droid
2. Lock on vehicle
3. Left click after lock tone
4. Be amazed as vehicles get nuked from one lock on

**Expected behavior**
Lock on launchers to not exist against ground vehicles.

**Screenshots**

**Mod List**
Standard 91st Modlist for Main Operations.

**Additional context**

**Comment by Grizzly-github** [comment]
ill deal with this tomorrow :)

**Comment by xxQal** [comment]
Just a Thought. But instead of outright removal. We Copy the Assault Droid, rename it to Heavy Assault Droid. The Heavy Assault would keep the Lock on. The Normal Assault would then run a RPS-6?

**Comment by DoctorDrugs** [comment]
Lock on AT is shit to deal with, there no trophy system or anything else that can deny the lock on AT. You have two choices to stop lock on AT drive 4km away from where it was launched from or use a hill, rock or structure to intercept the rocket. Getting killed from 3 km away because you either didn’t know you got locked into due to buggy ground sensors, lack of warning for the lock on, the missile dropping off radar or spam from lock on at is F shit to deal with.

it should be flat out removed, all the vehicles die to one lock on missile. Just add back the dumb fire rocket launchers we had with the old droid compositions we were using.
