### ISSUE TITLE
Rebalance Marksman weapon MOA's.

### ISSUE THREAD

**Issue by bardokyaeger** [91st-Aux-Team/MRC-issue-tracker#49]
**Is your feature request related to a problem? Please describe.**
Currently our marksman weapons seem to be a little over the board when it comes to their MOA, given that they are supposed to be precise weapons some seem to be not nearly as accurate as they should be.

**Describe the solution you'd like**
Update the MOA's to better reflect better weapons being unlocked through rank.

**Current listed MOAs:**
DC-15LE 2.5 MOA
DW-32 3.0 MOA
Firepuncher 0.3 MOA
Valken 38X 1.5 MOA
DC-15X 2.5 MOA

**Suggested MOA's**
DC-15LE 2.5 MOA
DW-32 2.0 MOA
Valken 38X 1.5 MOA
Firepuncher 1.0 MOA
DC-15X 0.5 MOA

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Grizzly-github** [comment]
this will be changed for the next testers update
