### ISSUE TITLE
[MRC] Valken-38X has access to a scope when using irons/other issues.

### ISSUE THREAD

**Issue by IchBinMiller** [91st-Aux-Team/MRC-issue-tracker#50]
When using the iron sights on the Valken 38x it still has access to a scope when using alternate sights. Said scope is also goes up to somewhere around 12x magnification

Resupply boxes, LAATs and don't carry ammo to resupply the Valken.

**Comment by Grizzly-github** [comment]
fixed Valken ammo missing from inventories/crates
