### ISSUE TITLE
B2's

### ISSUE THREAD

**Issue by Blackout-1806** [91st-Aux-Team/MRC-issue-tracker#51]
**Is your feature request related to a problem? Please describe.**
Massive upset about the spam of GL's

**Describe the solution you'd like**
Add different types of B2's gun (Blaster only) and B2's (Both guns and rockets) 

**Describe alternatives you've considered**
only 3 GL rounds and increase the health of B2's if possible 

**Additional context**
This doesn't just apply to B2's C-2 is interested in getting some type of enforcer for the CIS, some hard hitting and heavy health asset

**Comment by liamcannon** [comment]
Moving to testing.
