### ISSUE TITLE
DC-17s Default-Stun

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#54]
**Describe the bug**
Appon equiping the DC-17s, they are Default to the 2nd "3as Stun Barrel" instead of the Main Magazine.

**To Reproduce**
     Equip and try yourself

**Expected behavior**
 The Lethal mag being the default on pulling out the DC-15s

**Screenshots**
i can grab if you need later 

**Mod List**
Include the modlist you were running when this bug occured
default mainop

**Additional context**
IDK if feature or not. But I've gotten myself Claped due to it pulling out on stun (EVERY time I pull out the DC-17s) over the main lethal rounds.

**Comment by liamcannon** [comment]
I'm not able to replicate
