### ISSUE TITLE
GAT - Specificaly the AA & Light Varriants (Non Priority)

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#55]
**Is your feature request related to a problem? Please describe.**
The GAT Light, and GAT AA. Use the Same Model, however use different weapons. One is a MAJOR Threat to any and ALL units on the Field. The other is an inconvenience. 

**Describe the solution you'd like**
IK We dont have the SPPs/ability to currently make different markings/skins for them. I would like to Make the AA only available in the Olive Skin. and the GAT Light ONLY available in the CIS Skin (Or Vice Versa)

**Describe alternatives you've considered**
Making Zuse's Use only 1 or the other. However one of them is currently only available in one skin (Would have to double check, which is which.) It would just be Disabling the other version of the other.

**Additional context**
This is up for Request/Discussion

**Comment by liamcannon** [comment]
Done
