### ISSUE TITLE
Discussion | Cosmetics - WIP

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#56]
IK I Nuked the Format. This is honestly more for Discussion rather then standard Request.

I'm unhappy with how  most of our Vest, Faceware, and Helmets are Currently Grouped/Sorted. 
As well, How some things are in Vest. and some things are in Facewear.

I Would like your current thoughts on how they are. As well. Will be brining up how I think this Should be Organized (Going to be Making it a Google Doc so Its Slightly more Organized then I can Make this. AS I know it will be Long here.

The Main Things Are 
-The Standard Non Custom Cosmetics, Should be available in Faceware & Vests,
-Where did the "Invisible" Recon Vest Go?
-IK there was another thing - Will Fix when I remember Pushing so we can start this Discussion.

**Comment by liamcannon** [comment]
I've had this conversation with Frasier and Charred so many times

**Comment by xxQal** [comment]
That's probably true. However I certainty dont have all the information about this that you all discussed. & If we can decide / come to an Agreement on some things. I Can certainty back ya up. If you can provide sound reasoning on why we can't have certainty things as options. Then I Know I can Back it.

**Comment by xxQal** [comment]
So This is what I came up with For Catagories,
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/671286b9-f4e4-41b3-b77c-b93905a879ca)

**Comment by xxQal** [comment]
Just a Thought I had RN (An Option for Discussion)
Vests only being the "Standard" Equipment. and Facewear being Bilited Items/Custom
