### ISSUE TITLE
** HEAT RPS-6 Rockets are MIA in Ressuply

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#57]
**Describe the bug**
HEAT Rockets are not in the Resupply Inventory

**To Reproduce**
Look at an Explosive Resupply & LAAT/Vehicle Inventory

**Expected behavior**
RPS-6 HEAT Rockets be inside.

**Screenshots**
Can Grab Later (IK This was Posted in another Ticket that was Closed)

**Mod List**
Main OP Standard

**Additional context**
This is a Resubmit, as IK Its on another "Completed" Ticket.

**Comment by liamcannon** [comment]
I have no idea why these won't show up

**Comment by liamcannon** [comment]
@Grizzly-github can I close this now.
