### ISSUE TITLE
Z-95 gear and cokpit animation not working.

### ISSUE THREAD

**Issue by Deltateam70** [91st-Aux-Team/MRC-issue-tracker#59]
**Describe the bug**
When using the Z-95 the animation of the Z-95's cockpit and gear aren't working, they stay open and down, even if you bring gear up.

**To Reproduce**
Spawn in Z-95, get in, lift off and bring up landing gear. 

**Expected behavior**
Gear to retract into the airframe and the cockpit glass to close and not expose the pilot to fire.

**Screenshots**
Can grab a screenshot or a video if required.

**Mod List**
Include the modlist you were running when this bug occured
Standard modlist.

**Additional context**

**Comment by liamcannon** [comment]
Resolved, will be out next week.
