### ISSUE TITLE
Thermal Detonator Spacing Trainer

### ISSUE THREAD

**Issue by Tylinertobius** [91st-Aux-Team/MRC-issue-tracker#61]
People dont know how to space out sometimes so this may help.

A Thermal Detonator that has the same sound, looks the same etc, but doesnt actually do damage when it explodes, maybe a wee small thing if possible it says space out when it explodes.

We have repeatedly brought up spacing over and over and over again but it still is an issue.

**Comment by liamcannon** [comment]
Fart noise at the end 😄
