### ISSUE TITLE
Stun rounds going straight up.

### ISSUE THREAD

**Issue by StoicallyHyped** [91st-Aux-Team/MRC-issue-tracker#64]
**Describe the bug**
When shooting DC-17 stun rounds with certain kits the rounds shoot straight up then go backwards.

**To Reproduce**
Go into Ace Arsenal and choose any loadout with pistol stuns then shoot stuns. The shot trace should show them going straight up then backwards. Should happen with both short and long mags.

**Expected behavior**
Stuns go forward and hit the target.

**Screenshots**
![20240403165305_1](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/59328316/d4caeb62-f3f8-4d85-88a2-7ac2b8a0fbe9)
![20240403165319_1](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/59328316/bb9e3ab3-4f78-42da-8429-bf11d87ba987)

**Mod List**
Main Op modlist with "Kill Confirmed" and "Fluffy's 3D Map Markers" added

**Additional context**
Happened with pilot kit: 
[[[],[],["MRC_DC17s","","JLTS_DC17SA_flashlight","3AS_optic_holo_DC15S",["MRC_stun_mag_short",9],["JLTS_stun_mag_long",5],""],["MRC_pilot_uniform_CX",[["ACE_tourniquet",6],["MRC_Painkiller",4],["kat_IV_16",2],["ACE_epinephrine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["MRC_bacta_bag",2],["MRC_bacta_bag_500",4],["MRC_phase2_helmet_shark_hat",1]]],["MRC_phase2_vest_VCT",[["ACE_CableTie",5],["ACE_IR_Strobe_Item",1],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["3AS_ThermalDetonator",3,1],["MRC_45ACP_x20_mag",4,20]]],["MRC_phase2_backpack_cdv_nova",[["ACE_microDAGR",1],["WBK_HeadLampItem",1],["ToolKit",1],["ACE_Chemlight_HiGreen",2,1],["ACE_Chemlight_HiRed",2,1],["MRC_SmokeWhite",2,1],["MRC_SmokeGreen",2,1],["MRC_SmokeOrange",2,1],["MRC_SmokePurple",2,1],["MRC_SmokeRed",2,1],["MRC_SmokeYellow",2,1],["MRC_SmokeBlue",2,1],["MRC_SmokeBlack",2,1],["MRC_stun_mag_short",3,10],["MRC_45ACP_x20_mag",1,20]]],"MRC_pilot_helmet_CX","",["MRC_rangefinder_Unmarked_night","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","TFAR_microdagr",""]],[["aceax_textureOptions",[]],["ace_earplugs",true]]]

Other kits worked fine.

**Comment by liamcannon** [comment]
I was able to replicate it but not consistently

**Comment by StoicallyHyped** [comment]
Same for me, sometimes they'd bug out then I'd reload the kit again and they would work
