### ISSUE TITLE
Update 5.9.0 | Hailfire Droids

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#67]
**Describe the bug**
There are Several Issues here. Posting what I have Found.
- [MRC] IG-227 Hailfire Droid (Arty)
-- Spawns with a "Crew" of x5 B1 Driver Droids (Only 3 Seats: Driver,Gunner,Commander)
-- x3 of the Crew being in the "Commander Seat"
--"Working" Can Fire Main Weapon & Anti Personel Weapon
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/f67dca53-bba3-4216-b08f-6efa3858a236)

- [MRC] IG-227 Hailfire Droid (AT)
-- Has a Vissual Issue with the Anti Personel Weapon on the Front
-- Spawns with a "Crew" of x1 B1 Driver Droid  (ONLY 1 Seat: Driver)
-- Non Functioning Only can Drive
-- NON Spawnable in Zeus
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/4cdeccb7-95e0-4ff8-bf68-e97f37de32f2)

- [MRC] IG-227 Hailfire Droid (HE)
-- Has a Vissual Issue with the Anti Personel Weapon on the Front
-- Spawns with a "Crew" of x1 B1 Driver Droid  (ONLY 2 Seat: Driver, "Gunner" Unlabeled)
-- Non Functioning Only can Drive
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/c3b3cfab-27fd-4030-9caf-019be80dcf74)

- [MRC] IG-227 Hailfire Droid (SAM)
-- Spawns with a "Crew" of x5 B1 Driver Droids (Only 3 Seats: Driver,Gunner,Commander)
-- x3 of the Crew being in the "Commander Seat"
--"Working" Can Fire Main Weapon & Anti Personel Weapon
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/4e04b696-8106-4b1d-951b-88a3524e069d)

**To Reproduce**
Spawn them In

**Expected behavior**
Expected there be x3 Seats and only x3 Crew spawning with Each Hailfire Vehicle.

**Screenshots**
Posted Above

**Mod List**
Pinned Main Operation Modlist in main Discord

**Additional context**
NON Major Issue Posting here for Records & Possibility of Fix.

**Comment by Durzai** [comment]
Much like the OG-9, this was looked into in the past, but a solution was not found at that time for the issues above. We believe this is also an inheritance pathing issue, and will investigate further when a coder is available.
