### ISSUE TITLE
Update 5.9.0 |  OG9

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#68]
**Describe the bug**
OG9 is only Spawnable in Eden. 
No "AI" is Spawned when Placing

**To Reproduce**
Try and Spawn an OG9 in Eden & in Zues.

**Expected behavior**
Spawn with Crew and in Zues & Eden.

**Screenshots**

**Mod List**
Main Operation Modlist.

**Additional context**
I Cant Tell if the Weapon on the OG9 have sound or not.

**Comment by Durzai** [comment]
This item was looked into in the past, but we could not find a solution to the issue of AI not spawning when placed. It has not been forgotten, and will be looked into again when time permits. We believe it had to do with inheritance pathing, and will investigate that line of correction when able.
