### ISSUE TITLE
Update 5.9.0 | Republic Equipment

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#70]
**Describe the bug**
- The Canister Rounds are MIA from the Arsenal & the Loadable Ammo  for the RPS-6
- The WO4 & All Jump Trooper Kama's all Still have Dirt.
- Sound's Helmet "Shown" under P2 & Munka Helmets.
**To Reproduce**
Look for the Ammo in the Arsenel
Look at the Jumptrooper & WO4 Kama's 

**Expected behavior**
Removed Dirt
Canister Round Available

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/f7a8fa10-681b-4908-b939-4c7d42c38ea1)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/e1d6c64e-ccda-4fb5-be94-dd85826ef250)

**Mod List**
Main Operation Pinned in Main Discord.

**Additional context**
IK we had our Different Views on the Canister Round. Saw you made an "edit" to it but I can't Find it.

**Comment by liamcannon** [comment]
I cannot get these canister rounds to show up idk why.
