### ISSUE TITLE
DP-23 Shotgun Update

### ISSUE THREAD

**Issue by CSMPredatorz** [91st-Aux-Team/MRC-issue-tracker#71]
Update Fire Rate in line with this mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=1663731813

Mag Increase for Slugs to 10Rnd Buckshot to 16 Rounds. 

Range based off of 2rnd Slug and Buck Damage Tables from Contact DLC Shotgun Kozlice 12g. Should give effective range of 100m for Slugs and 75m for Buck Shot.

**Comment by Grizzly-github** [comment]
done
