### ISSUE TITLE
.model error when placing MRC crates in eden (fatal)

### ISSUE THREAD

**Issue by Baconbitz94** [91st-Aux-Team/MRC-issue-tracker#72]
**Describe the bug**

**To Reproduce**
1. create an MP scenario in eden (player slots, a respawn point, etc.)
2. place down the MRC supply crates (explosive, medical, ammo) ("MRC_supplies_Resupply_Box_Ammo", 
"MRC_supplies_Resupply_Box_Explosives", 
"MRC_supplies_Resupply_Box_Medical")
3. save scenario
4. play scenario in MP
5. be presented with error (local hosts will be able to proceed, but in the past this error message has been fatal on dedicated servers, effectively breaking the mission file) 

**Expected behavior**
I would expect our in-house supply crates to placeable in the Eden editor 
**Screenshots** These screenshots are from a barebones scenario i made on Altis to reproduce the issue- if you want the pbo lmk
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/143630633/b42b130d-8767-4f8f-b7e6-3cce7f74b43e)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/143630633/f801f2d9-8868-4d16-92cd-732a5248814b)

**Mod List**
Github no likey HTML, attaching notepad but if you want an html lmk
[Arma 3 Preset 91stmm.txt](https://github.com/91st-Aux-Team/MRC-issue-tracker/files/15254180/Arma.3.Preset.91stmm.txt)

**Additional context**
hugs and kisses ty

**Comment by Grizzly-github** [comment]
@Durzai You're rewrite of the supplies PBO should fix this.
