### ISSUE TITLE
Add Impulse to new 3AS vehicles 

### ISSUE THREAD

**Issue by Blackout-1806** [91st-Aux-Team/MRC-issue-tracker#76]
With the new 3AS update it has brought me some new toys that I enjoy and was looking to see if they could be ported over to the aux mod 

the MAF Looking to get impulse we use for it to make it good

Next up is the Aegis Transport (Both Types) same as the MAF all it really needs is a good impulse could be slowed down like the Rho as its mostly a freighter

**Comment by CL-Jericho** [comment]
Impulse added to both vehicles as part of branch CIS-Aircraft
