### ISSUE TITLE
Beskar Kunda Commander Turret will turn the vehicle engine on whenever it moves

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#8]
**Describe the bug**
as the title of the bug report states, any movement of the commander seat turret on the kunda will force turn the engine on.

**To Reproduce**
1. Hop into Kunda Commander Seat
2. Turn turret
3. Be amazed as the turret turns on the engine

**Expected behavior**
not have a commander seat forcefully turn the vehicle engine on

**Screenshots**

**Mod List**
normal modlist with small extras like ch view distance

**Additional context**
cannon is stinky

**Comment by DoctorDrugs** [comment]
multiple vehicle commander turrets have this behavior now, unknown the source of it. can confirm bantha commander turret does this

**Comment by liamcannon** [comment]
@DoctorDrugs does this behavior happen on vanilla vics as well?
