### ISSUE TITLE
one way shield

### ISSUE THREAD

**Issue by Blackout-1806** [91st-Aux-Team/MRC-issue-tracker#82]
**Is your feature request related to a problem? Please describe.**
nothing on you guys but there is a 500 Planetary Shield but 3as only have one way shield for 50-100 would be neat to get all the way up to 500 one way shield that allows the mission makers to make a larger and more difficult Objective 

**Describe the solution you'd like**
one way shield gets added 

**Describe alternatives you've considered**
N/A

**Comment by Durzai** [comment]
Unable to help, 3AS models are not within our wheelhouse. Would suggest making this request in the 3AS discord.
