### ISSUE TITLE
Helmet and Armor removals

### ISSUE THREAD

**Issue by Anxxnymous** [91st-Aux-Team/MRC-issue-tracker#84]
**Pilot Helmets**
- Arcane
- Crimmy
- Delta
- Oxide
- Thunderbolt

**ARC Helmets**
- Cannon
- Miller
- Roach (no model, but is in compat)
- Scorch
- Trauma

**ATRT Helmets**
- Baker
- Kuro
- Weylyn

**BARC Helmets**
- Blossom
- Goose
- Merit
- Mav
- Shank
- Snapper
- Wagner

**P2 Helmets**
- Awake
- Con
- Galahad
- Gray
- Postal
- Roach
- Scar
- Scorch
- Stoic
- Sytha
- Volx
(Tig's Helmet is in P2 when it should be in Jumptrooper)

**Jumptrooper Helmets**
- Samael

**Vests**
- Gray's Kama
- Weylyn's Kama
- Mav's Officer Pauldron set

**Custom Armors**
- Cannon
- Gray
- Roach
- Scorch (Base and Scorch ARC)

**Comment by xxQal** [comment]
- Mav, Scorch, & Other Former UCs equipment is being Keep for C-3 & C-2 Uses (Would love to Request that they be moved to a new location)
