### ISSUE TITLE
Gozanti from 3as

### ISSUE THREAD

**Issue by Blackout-1806** [91st-Aux-Team/MRC-issue-tracker#89]
**Is your feature request related to a problem? Please describe.**
I was looking to see if we can get the Gozanti Class Cruiser from 3as put in our modlist as a indi craft and added armor just more durable as right now it is pretty weak

**Describe the solution you'd like**
Add the Gozanti Class Cruiser over to our Aux mod and buff its health 

**Describe alternatives you've considered**
N/A not the biggest need just something I thought was cool

**Comment by Durzai** [comment]
3AS fixed their balance issues, MRC variant no longer necessary.
