### ISSUE TITLE
Server reporting ACE medical issues with 91st droids

### ISSUE THREAD

**Issue by DoctorDrugs** [91st-Aux-Team/MRC-issue-tracker#9]
**Describe the bug**
Server logs spit out errors with ACE medical and 91st Droids regarding bad hitpoints

**To Reproduce**
1. Join Main Operation Server
2. Spawn in 91st Droids as Zeus
3. Check RPTs to confirm the error is there

**Expected behavior**
Not to see logs of ace medical issues

**Screenshots**

**Mod List**
91st Main Operation Server Mod List

**Additional context**
Will be retesting again on the servers shortly here just in case this is still an issue, Server mods were updated as a precaution regardless of them already being up to date. If the issue is solved from that I will self close the Issue.

**Comment by DoctorDrugs** [comment]
lack of errors popping up after forcing an ACE update, hopefully that's not a thing on 9/2/23

**Comment by liamcannon** [comment]
@DoctorDrugs this will be resolved in the units update
